version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"  # Utilisation de la variable d'environnement pour le port
    networks:
      - mongo_network
    volumes:
      - mongodb_data:/data/db  # Volume pour les données persistantes de MongoDB
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Script d'initialisation pour MongoDB
    env_file: 
      - .env  # Charge toutes les variables d'environnement du fichier .env
    restart: unless-stopped

  app:
    build: .
    container_name: python_app
    depends_on:
      - mongodb
    networks:
      - mongo_network
    env_file: 
      - .env  # Charge toutes les variables d'environnement du fichier .env
    volumes:
      - ./script.py:/usr/src/app/script.py  # Montée du script Python
      - ./healthcare_dataset.csv:/usr/src/app/healthcare_dataset.csv  # Montée du fichier CSV
    restart: on-failure

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
